# This list is used to populate the tables articles.
# Please feel free to adjust
# The product list contains tuples of product names, product categories and price
# The primary key (product_id) will be generated automatically

products = [
    ('Jeans', 'Clothes', 30.73),
    ('Smartwatch', 'Electronics', 120.46),
    ('Coffee Maker', 'Home and Kitchen', 40.3),
    ('Basketball', 'Sports and Outdoors', 80.96),
    ('Sunglasses', 'Fashion', 30.99),
    ('Facial Moisturizer', 'Beauty', 5.56),
    ('Building Blocks', 'Toys', 20.34),
    ('Fitness Tracker', 'Health', 80.9),
    ('Car Wax', 'Automotive', 20.64),
    ('Mystery Novel', 'Books', 15.58),
    ('Garden Hose', 'Garden', 30.77),
    ('Portable Speaker', 'Electronics', 50.22),
    ('Blender', 'Home and Kitchen', 20.92),
    ('Running Shoes', 'Sports and Outdoors', 160.56),
    ('Leather Jacket', 'Fashion', 120.14),
    ('Shampoo', 'Beauty', 4.12),
    ('Board Game', 'Toys', 15.36),
    ('Blood Pressure Monitor', 'Health', 120.57),
    ('Car Air Freshener', 'Automotive', 7.66),
    ('Cookbook', 'Books', 8.65),
    ('Lawn Mower', 'Garden', 150.44),
    ('Headphones', 'Electronics', 30.92),
    ('Toaster', 'Home and Kitchen', 41),
    ('Tent', 'Sports and Outdoors', 180.5),
    ('Wristwatch', 'Fashion', 130.35),
    ('Lipstick', 'Beauty', 15.73),
    ('Action Figure', 'Toys', 8.61),
    ('Yoga Mat', 'Health', 15.51),
    ('Car Charger', 'Automotive', 30.07),
    ('Travel Guide', 'Books', 12.94),
    ('Fertilizer', 'Garden', 15.91),
    ('Laptop', 'Electronics', 1200.91),
    ('Microwave Oven', 'Home and Kitchen', 40.65),
    ('Bicycle', 'Sports and Outdoors', 400.52),
    ('Winter Coat', 'Fashion', 150.88),
    ('Sunscreen', 'Beauty', 15.14),
    ('Puzzle', 'Toys', 8.39),
    ('Weight Scale', 'Health', 20.36),
    ('Tire Pressure Gauge', 'Automotive', 30.6),
    ('Cookware Set', 'Home and Kitchen', 70.81),
    ('Backpack', 'Fashion', 30.9),
    ('Perfume', 'Beauty', 70.67),
    ('Remote Control Car', 'Toys', 30.92),
    ('Resistance Bands', 'Health', 40.32),
    ('GPS Navigator', 'Automotive', 90.33),
    ('Plant Seeds', 'Garden', 40.06),
    ('Smartphone', 'Electronics', 700.85),
    ('Coffee Grinder', 'Home and Kitchen', 20.1),
    ('Camping Lantern', 'Sports and Outdoors', 60.98),
    ('Scarves', 'Fashion', 20),
    ('Nail Polish', 'Beauty', 30.63),
    ('Educational Toy', 'Toys', 40.79),
    ('Protein Powder', 'Health', 30.34),
    ('Car Floor Mats', 'Automotive', 60.92),
    ('DIY Home Repair Book', 'Books', 40.32),
    ('Fountain Pen', 'Office Supplies', 20.12),
    ('Swimwear', 'Fashion', 30.99),
    ('Hair Dryer', 'Beauty', 50.44),
    ('Chess Set', 'Toys', 35.73),
    ('Vitamin Supplements', 'Health', 60.36),
    ('Car Jump Starter', 'Automotive', 30.37),
    ('Desk Lamp', 'Home and Kitchen', 150.33),
    ('Running Jacket', 'Sports and Outdoors', 80.98),
    ('Watch Box', 'Fashion', 30.25),
    ('Lip Balm', 'Beauty', 20.35),
    ('Dollhouse', 'Toys', 70.67),
    ('First Aid Kit', 'Health', 30.44),
    ('Carpet Cleaner', 'Automotive', 40.09),
    ('Novel', 'Books', 8.47),
    ('Potted Plant', 'Garden', 5.01),
    ('Robot Vacuum', 'Electronics', 250.87),
    ('Sandwich Maker', 'Home and Kitchen', 40.8),
    ('Cycling Helmet', 'Sports and Outdoors', 30.38),
    ('Wallet', 'Fashion', 20.37),
    ('Makeup Brushes', 'Beauty', 30.55),
    ('Artificial Christmas Tree', 'Home Decor', 40.73),
    ('Telescope', 'Hobbies', 350.58),
    ('Humidifier', 'Health', 47.11),
    ('Car Wash Kit', 'Automotive', 25.05),
    ('Cooking Utensils', 'Home and Kitchen', 90.3),
    ('Tennis Racket', 'Sports and Outdoors', 350.55),
    ('Sleepwear', 'Fashion', 30.96),
    ('Cologne', 'Beauty', 50.48),
    ('Kite', 'Toys', 70.18),
    ('Car Window Shade', 'Automotive', 30.75),
    ('Graphic Novel', 'Books', 20.72),
    ('Outdoor String Lights', 'Garden', 50.71),
    ('Gaming Mouse', 'Electronics', 35.4),
    ('Juicer', 'Home and Kitchen', 45.23),
    ('Hiking Boots', 'Sports and Outdoors', 130.31),
    ('Handbag', 'Fashion', 700.82),
    ('Face Mask', 'Beauty', 25.6),
    ('Musical Instrument', 'Toys', 55.83),
    ('Weighted Blanket', 'Health', 35.38),
    ('Car Air Purifier', 'Automotive', 15.99),
    ('Lawn Fertilizer', 'Garden', 15.83),
    ('Smart Thermostat', 'Electronics', 35.73),
    ('Hair Straightener', 'Beauty', 45.82),
    ('Remote Control Drone', 'Toys', 180.77),
    ('Yoga Block', 'Health', 25.78),
    ('Car Phone Mount', 'Automotive', 35.52),
    ('Water Bottle', 'Outdoor Accessories', 7.01),
    ('Fiction Book', 'Books', 8.87),
    ('Herb Garden Kit', 'Garden', 14.28),
    ('Smart Doorbell', 'Home Improvement', 170.94),
    ('Espresso Machine', 'Home and Kitchen', 230.89),
    ('Baseball Glove', 'Sports and Outdoors', 25.02),
    ('Winter Boots', 'Fashion', 55.47),
    ('Eyeliner', 'Beauty', 25.04),
    ('RC Car', 'Toys', 30.58),
    ('Car Seat Cover', 'Automotive', 20.19),
    ('Cooking Thermometer', 'Kitchen Gadgets', 25.1),
    ('Indoor Plants', 'Garden', 35.8),
    ('Wireless Earbuds', 'Electronics', 55.62),
    ('Grill Pan', 'Home and Kitchen', 35.38),
    ('Camping Tent', 'Sports and Outdoors', 250.03),
    ('Sweater', 'Fashion', 45.12),
    ('Nail File Set', 'Beauty', 35.3),
    ('Educational Puzzle', 'Toys', 25.77),
    ('Protein Bars', 'Health', 7.15),
    ('Car Tool Kit', 'Automotive', 170.33),
    ('Self-Help Book', 'Books', 15.29),
    ('Garden Gloves', 'Garden', 8.02),
    ('Smart Lock', 'Home Improvement', 250.6),
    ('Air Fryer', 'Home and Kitchen', 250.92),
    ('Cycling Gloves', 'Sports and Outdoors', 30.13),
    ('Necktie', 'Fashion', 45.04),
    ('Makeup Remover', 'Beauty', 12.28),
    ('Building Blocks Set', 'Toys', 35.27),
    ('Exercise Ball', 'Health', 13.93),
    ('Car Seat Organizer', 'Automotive', 25.06),
    ('Travel Journal', 'Books', 35.55),
    ('Patio Furniture', 'Outdoor Living', 251),
    ('Wireless Mouse', 'Electronics', 15.02),
    ('Slow Cooker', 'Home and Kitchen', 65.7),
    ('Hiking Backpack', 'Sports and Outdoors', 80.13),
    ('Watch', 'Fashion', 40.23),
    ('Mascara', 'Beauty', 20.08),
    ('Resistance Bands Set', 'Health', 35.1),
    ('Car Phone Charger', 'Automotive', 65.97),
    ('Outdoor Bench', 'Garden', 130.6),
    ('Smart Speaker', 'Electronics', 140.05),
    ('Coffee Table', 'Home and Kitchen', 180.38),
    ('Soccer Ball', 'Sports and Outdoors', 87.41),
    ('Jacket', 'Fashion', 117.95)
]